version: '3.2'

services:
  db:
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    
  adminer:
    image: adminer
    ports:
      - "4080:8080"
    restart: always

volumes:
  mysql: